$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Azure ML extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Azure ML job
      run: |
        az ml job create --file src/job.yml -- local --web  --resource-group mlops-adrian --workspace-name mlops-workspace-learning


